/*
 * generated by Xtext 2.25.0
 */
package hwo.evtool.dsl.ide.contentassist.antlr;

import com.google.common.collect.ImmutableMap;
import com.google.inject.Inject;
import com.google.inject.Singleton;
import hwo.evtool.dsl.ide.contentassist.antlr.internal.InternalEvaluacionParser;
import hwo.evtool.dsl.services.EvaluacionGrammarAccess;
import java.util.Map;
import org.eclipse.xtext.AbstractElement;
import org.eclipse.xtext.ide.editor.contentassist.antlr.AbstractContentAssistParser;

public class EvaluacionParser extends AbstractContentAssistParser {

	@Singleton
	public static final class NameMappings {
		
		private final Map<AbstractElement, String> mappings;
		
		@Inject
		public NameMappings(EvaluacionGrammarAccess grammarAccess) {
			ImmutableMap.Builder<AbstractElement, String> builder = ImmutableMap.builder();
			init(builder, grammarAccess);
			this.mappings = builder.build();
		}
		
		public String getRuleName(AbstractElement element) {
			return mappings.get(element);
		}
		
		private static void init(ImmutableMap.Builder<AbstractElement, String> builder, EvaluacionGrammarAccess grammarAccess) {
			builder.put(grammarAccess.getCriterioAccess().getAlternatives(), "rule__Criterio__Alternatives");
			builder.put(grammarAccess.getAtomoAccess().getAlternatives(), "rule__Atomo__Alternatives");
			builder.put(grammarAccess.getAtomoAccess().getValorAlternatives_2_1_0(), "rule__Atomo__ValorAlternatives_2_1_0");
			builder.put(grammarAccess.getCmpntEvaluacionAccess().getGroup(), "rule__CmpntEvaluacion__Group__0");
			builder.put(grammarAccess.getCmpntEvaluacionAccess().getGroup_2(), "rule__CmpntEvaluacion__Group_2__0");
			builder.put(grammarAccess.getCriterioTypeAccess().getGroup(), "rule__CriterioType__Group__0");
			builder.put(grammarAccess.getCriterioTypeAccess().getGroup_4(), "rule__CriterioType__Group_4__0");
			builder.put(grammarAccess.getAtomoAccess().getGroup_0(), "rule__Atomo__Group_0__0");
			builder.put(grammarAccess.getAtomoAccess().getGroup_1(), "rule__Atomo__Group_1__0");
			builder.put(grammarAccess.getAtomoAccess().getGroup_2(), "rule__Atomo__Group_2__0");
			builder.put(grammarAccess.getComplejoTypeAccess().getGroup(), "rule__ComplejoType__Group__0");
			builder.put(grammarAccess.getEvaluacionModelAccess().getComponentesAssignment(), "rule__EvaluacionModel__ComponentesAssignment");
			builder.put(grammarAccess.getCmpntEvaluacionAccess().getNameAssignment_1(), "rule__CmpntEvaluacion__NameAssignment_1");
			builder.put(grammarAccess.getCmpntEvaluacionAccess().getSuperTypeAssignment_2_1(), "rule__CmpntEvaluacion__SuperTypeAssignment_2_1");
			builder.put(grammarAccess.getCmpntEvaluacionAccess().getAtributosAssignment_4(), "rule__CmpntEvaluacion__AtributosAssignment_4");
			builder.put(grammarAccess.getAtributosAccess().getCriteriosAssignment(), "rule__Atributos__CriteriosAssignment");
			builder.put(grammarAccess.getCriterioTypeAccess().getNameAssignment_1(), "rule__CriterioType__NameAssignment_1");
			builder.put(grammarAccess.getCriterioTypeAccess().getExpresionAssignment_3(), "rule__CriterioType__ExpresionAssignment_3");
			builder.put(grammarAccess.getCriterioTypeAccess().getSoporteAssignment_4_1(), "rule__CriterioType__SoporteAssignment_4_1");
			builder.put(grammarAccess.getAtomoAccess().getValorAssignment_0_1(), "rule__Atomo__ValorAssignment_0_1");
			builder.put(grammarAccess.getAtomoAccess().getValorAssignment_1_1(), "rule__Atomo__ValorAssignment_1_1");
			builder.put(grammarAccess.getAtomoAccess().getValorAssignment_2_1(), "rule__Atomo__ValorAssignment_2_1");
			builder.put(grammarAccess.getComplejoTypeAccess().getNameAssignment_1(), "rule__ComplejoType__NameAssignment_1");
			builder.put(grammarAccess.getComplejoTypeAccess().getComponenteAssignment_2(), "rule__ComplejoType__ComponenteAssignment_2");
		}
	}
	
	@Inject
	private NameMappings nameMappings;

	@Inject
	private EvaluacionGrammarAccess grammarAccess;

	@Override
	protected InternalEvaluacionParser createParser() {
		InternalEvaluacionParser result = new InternalEvaluacionParser(null);
		result.setGrammarAccess(grammarAccess);
		return result;
	}

	@Override
	protected String getRuleName(AbstractElement element) {
		return nameMappings.getRuleName(element);
	}

	@Override
	protected String[] getInitialHiddenTokens() {
		return new String[] { "RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT" };
	}

	public EvaluacionGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(EvaluacionGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
	
	public NameMappings getNameMappings() {
		return nameMappings;
	}
	
	public void setNameMappings(NameMappings nameMappings) {
		this.nameMappings = nameMappings;
	}
}
