/*
 * generated by Xtext 2.25.0
 */
package hwo.evtool.dsl.ui.tests;

import com.google.inject.Injector;
import hwo.evtool.dsl.evaluacion.ui.internal.EvaluacionActivator;
import org.eclipse.xtext.testing.IInjectorProvider;

public class EvaluacionUiInjectorProvider implements IInjectorProvider {

	@Override
	public Injector getInjector() {
		return EvaluacionActivator.getInstance().getInjector("hwo.evtool.dsl.Evaluacion");
	}

}
