/**
 * generated by Xtext 2.25.0
 */
package hwo.evtool.dsl.evaluacion;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Calificar Otros</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link hwo.evtool.dsl.evaluacion.CalificarOtros#getValor <em>Valor</em>}</li>
 *   <li>{@link hwo.evtool.dsl.evaluacion.CalificarOtros#getComentario <em>Comentario</em>}</li>
 * </ul>
 *
 * @see hwo.evtool.dsl.evaluacion.EvaluacionPackage#getCalificarOtros()
 * @model
 * @generated
 */
public interface CalificarOtros extends Expresion
{
  /**
   * Returns the value of the '<em><b>Valor</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Valor</em>' attribute.
   * @see #setValor(int)
   * @see hwo.evtool.dsl.evaluacion.EvaluacionPackage#getCalificarOtros_Valor()
   * @model
   * @generated
   */
  int getValor();

  /**
   * Sets the value of the '{@link hwo.evtool.dsl.evaluacion.CalificarOtros#getValor <em>Valor</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Valor</em>' attribute.
   * @see #getValor()
   * @generated
   */
  void setValor(int value);

  /**
   * Returns the value of the '<em><b>Comentario</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Comentario</em>' attribute.
   * @see #setComentario(String)
   * @see hwo.evtool.dsl.evaluacion.EvaluacionPackage#getCalificarOtros_Comentario()
   * @model
   * @generated
   */
  String getComentario();

  /**
   * Sets the value of the '{@link hwo.evtool.dsl.evaluacion.CalificarOtros#getComentario <em>Comentario</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Comentario</em>' attribute.
   * @see #getComentario()
   * @generated
   */
  void setComentario(String value);

} // CalificarOtros
