/**
 * generated by Xtext 2.25.0
 */
package hwo.evtool.dsl.evaluacion;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Complejo Type</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link hwo.evtool.dsl.evaluacion.ComplejoType#getComponente <em>Componente</em>}</li>
 * </ul>
 *
 * @see hwo.evtool.dsl.evaluacion.EvaluacionPackage#getComplejoType()
 * @model
 * @generated
 */
public interface ComplejoType extends EObject
{
  /**
   * Returns the value of the '<em><b>Componente</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Componente</em>' reference.
   * @see #setComponente(CmpntEvaluacion)
   * @see hwo.evtool.dsl.evaluacion.EvaluacionPackage#getComplejoType_Componente()
   * @model
   * @generated
   */
  CmpntEvaluacion getComponente();

  /**
   * Sets the value of the '{@link hwo.evtool.dsl.evaluacion.ComplejoType#getComponente <em>Componente</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Componente</em>' reference.
   * @see #getComponente()
   * @generated
   */
  void setComponente(CmpntEvaluacion value);

} // ComplejoType
