/**
 * generated by Xtext 2.24.0
 */
package hwo.evtool.dsl.evaluacion;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Evaluaciones</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link hwo.evtool.dsl.evaluacion.Evaluaciones#getName <em>Name</em>}</li>
 *   <li>{@link hwo.evtool.dsl.evaluacion.Evaluaciones#getExpresion <em>Expresion</em>}</li>
 *   <li>{@link hwo.evtool.dsl.evaluacion.Evaluaciones#getComentario <em>Comentario</em>}</li>
 * </ul>
 *
 * @see hwo.evtool.dsl.evaluacion.EvaluacionPackage#getEvaluaciones()
 * @model
 * @generated
 */
public interface Evaluaciones extends EObject
{
  /**
   * Returns the value of the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Name</em>' attribute.
   * @see #setName(String)
   * @see hwo.evtool.dsl.evaluacion.EvaluacionPackage#getEvaluaciones_Name()
   * @model
   * @generated
   */
  String getName();

  /**
   * Sets the value of the '{@link hwo.evtool.dsl.evaluacion.Evaluaciones#getName <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Name</em>' attribute.
   * @see #getName()
   * @generated
   */
  void setName(String value);

  /**
   * Returns the value of the '<em><b>Expresion</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Expresion</em>' containment reference.
   * @see #setExpresion(Expresion)
   * @see hwo.evtool.dsl.evaluacion.EvaluacionPackage#getEvaluaciones_Expresion()
   * @model containment="true"
   * @generated
   */
  Expresion getExpresion();

  /**
   * Sets the value of the '{@link hwo.evtool.dsl.evaluacion.Evaluaciones#getExpresion <em>Expresion</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Expresion</em>' containment reference.
   * @see #getExpresion()
   * @generated
   */
  void setExpresion(Expresion value);

  /**
   * Returns the value of the '<em><b>Comentario</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Comentario</em>' attribute.
   * @see #setComentario(String)
   * @see hwo.evtool.dsl.evaluacion.EvaluacionPackage#getEvaluaciones_Comentario()
   * @model
   * @generated
   */
  String getComentario();

  /**
   * Sets the value of the '{@link hwo.evtool.dsl.evaluacion.Evaluaciones#getComentario <em>Comentario</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Comentario</em>' attribute.
   * @see #getComentario()
   * @generated
   */
  void setComentario(String value);

} // Evaluaciones
