/**
 * generated by Xtext 2.25.0
 */
package hwo.evtool.dsl.evaluacion;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Expresion</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see hwo.evtool.dsl.evaluacion.EvaluacionPackage#getExpresion()
 * @model
 * @generated
 */
public interface Expresion extends EObject
{
} // Expresion
