/**
 * generated by Xtext 2.25.0
 */
package hwo.evtool.dsl.evaluacion;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Int Constant</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see hwo.evtool.dsl.evaluacion.EvaluacionPackage#getIntConstant()
 * @model
 * @generated
 */
public interface IntConstant extends Atomo
{
} // IntConstant
