/*
 * generated by Xtext 2.25.0
 */
package hwo.evtool.dsl.evalcn.ui.tests;

import com.google.inject.Injector;
import hwo.evtool.dsl.evalcn.ui.internal.EvalcnActivator;
import org.eclipse.xtext.testing.IInjectorProvider;

public class EvaluacionUiInjectorProvider implements IInjectorProvider {

	@Override
	public Injector getInjector() {
		return EvalcnActivator.getInstance().getInjector("hwo.evtool.dsl.evalcn.Evaluacion");
	}

}
