/*
 * generated by Xtext 2.25.0
 */
package hwo.evtool.dsl.evalcn.web;

import org.eclipse.xtext.web.server.DefaultWebModule;

/**
 * Manual modifications go to {@link EvaluacionWebModule}.
 */
@SuppressWarnings("all")
public abstract class AbstractEvaluacionWebModule extends DefaultWebModule {

}
