/*
 * generated by Xtext 2.25.0
 */
package hwo.evtool.dsl.evalcn.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
public class EvaluacionUiModule extends AbstractEvaluacionUiModule {

	public EvaluacionUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
