/*
 * generated by Xtext 2.25.0
 */
package hwo.evtool.dsl.evalcn.validation;

import java.util.ArrayList;
import java.util.List;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.xtext.validation.AbstractDeclarativeValidator;

public abstract class AbstractEvaluacionValidator extends AbstractDeclarativeValidator {
	
	@Override
	protected List<EPackage> getEPackages() {
		List<EPackage> result = new ArrayList<EPackage>();
		result.add(hwo.evtool.dsl.evalcn.evaluacion.EvaluacionPackage.eINSTANCE);
		return result;
	}
}
