/**
 * generated by Xtext 2.25.0
 */
package hwo.evtool.dsl.evalcn.evaluacion;

import org.eclipse.emf.ecore.EAttribute;
import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EEnum;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.emf.ecore.EReference;

/**
 * <!-- begin-user-doc -->
 * The <b>Package</b> for the model.
 * It contains accessors for the meta objects to represent
 * <ul>
 *   <li>each class,</li>
 *   <li>each feature of each class,</li>
 *   <li>each enum,</li>
 *   <li>and each data type</li>
 * </ul>
 * <!-- end-user-doc -->
 * @see hwo.evtool.dsl.evalcn.evaluacion.EvaluacionFactory
 * @model kind="package"
 * @generated
 */
public interface EvaluacionPackage extends EPackage
{
  /**
   * The package name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNAME = "evaluacion";

  /**
   * The package namespace URI.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_URI = "http://www.evtool.hwo/dsl/evalcn/Evaluacion";

  /**
   * The package namespace name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_PREFIX = "evaluacion";

  /**
   * The singleton instance of the package.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  EvaluacionPackage eINSTANCE = hwo.evtool.dsl.evalcn.evaluacion.impl.EvaluacionPackageImpl.init();

  /**
   * The meta object id for the '{@link hwo.evtool.dsl.evalcn.evaluacion.impl.MaquinaEstadosImpl <em>Maquina Estados</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see hwo.evtool.dsl.evalcn.evaluacion.impl.MaquinaEstadosImpl
   * @see hwo.evtool.dsl.evalcn.evaluacion.impl.EvaluacionPackageImpl#getMaquinaEstados()
   * @generated
   */
  int MAQUINA_ESTADOS = 0;

  /**
   * The feature id for the '<em><b>Events</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MAQUINA_ESTADOS__EVENTS = 0;

  /**
   * The feature id for the '<em><b>Reset Events</b></em>' reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MAQUINA_ESTADOS__RESET_EVENTS = 1;

  /**
   * The feature id for the '<em><b>Commands</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MAQUINA_ESTADOS__COMMANDS = 2;

  /**
   * The feature id for the '<em><b>States</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MAQUINA_ESTADOS__STATES = 3;

  /**
   * The number of structural features of the '<em>Maquina Estados</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MAQUINA_ESTADOS_FEATURE_COUNT = 4;

  /**
   * The meta object id for the '{@link hwo.evtool.dsl.evalcn.evaluacion.impl.EventoImpl <em>Evento</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see hwo.evtool.dsl.evalcn.evaluacion.impl.EventoImpl
   * @see hwo.evtool.dsl.evalcn.evaluacion.impl.EvaluacionPackageImpl#getEvento()
   * @generated
   */
  int EVENTO = 1;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EVENTO__NAME = 0;

  /**
   * The feature id for the '<em><b>Code</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EVENTO__CODE = 1;

  /**
   * The number of structural features of the '<em>Evento</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EVENTO_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link hwo.evtool.dsl.evalcn.evaluacion.impl.ComponenteImpl <em>Componente</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see hwo.evtool.dsl.evalcn.evaluacion.impl.ComponenteImpl
   * @see hwo.evtool.dsl.evalcn.evaluacion.impl.EvaluacionPackageImpl#getComponente()
   * @generated
   */
  int COMPONENTE = 2;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int COMPONENTE__NAME = 0;

  /**
   * The feature id for the '<em><b>Actions</b></em>' reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int COMPONENTE__ACTIONS = 1;

  /**
   * The feature id for the '<em><b>Transitions</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int COMPONENTE__TRANSITIONS = 2;

  /**
   * The number of structural features of the '<em>Componente</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int COMPONENTE_FEATURE_COUNT = 3;

  /**
   * The meta object id for the '{@link hwo.evtool.dsl.evalcn.evaluacion.impl.ExpresionImpl <em>Expresion</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see hwo.evtool.dsl.evalcn.evaluacion.impl.ExpresionImpl
   * @see hwo.evtool.dsl.evalcn.evaluacion.impl.EvaluacionPackageImpl#getExpresion()
   * @generated
   */
  int EXPRESION = 3;

  /**
   * The feature id for the '<em><b>Tipo</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EXPRESION__TIPO = 0;

  /**
   * The feature id for the '<em><b>Comentario</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EXPRESION__COMENTARIO = 1;

  /**
   * The number of structural features of the '<em>Expresion</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EXPRESION_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link hwo.evtool.dsl.evalcn.evaluacion.impl.TipoEvaluacionImpl <em>Tipo Evaluacion</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see hwo.evtool.dsl.evalcn.evaluacion.impl.TipoEvaluacionImpl
   * @see hwo.evtool.dsl.evalcn.evaluacion.impl.EvaluacionPackageImpl#getTipoEvaluacion()
   * @generated
   */
  int TIPO_EVALUACION = 4;

  /**
   * The feature id for the '<em><b>Evaluacion</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TIPO_EVALUACION__EVALUACION = 0;

  /**
   * The number of structural features of the '<em>Tipo Evaluacion</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TIPO_EVALUACION_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link hwo.evtool.dsl.evalcn.evaluacion.impl.TransicionImpl <em>Transicion</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see hwo.evtool.dsl.evalcn.evaluacion.impl.TransicionImpl
   * @see hwo.evtool.dsl.evalcn.evaluacion.impl.EvaluacionPackageImpl#getTransicion()
   * @generated
   */
  int TRANSICION = 5;

  /**
   * The feature id for the '<em><b>Event</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TRANSICION__EVENT = 0;

  /**
   * The feature id for the '<em><b>State</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TRANSICION__STATE = 1;

  /**
   * The number of structural features of the '<em>Transicion</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TRANSICION_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link hwo.evtool.dsl.evalcn.evaluacion.impl.EvaluacionImpl <em>Evaluacion</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see hwo.evtool.dsl.evalcn.evaluacion.impl.EvaluacionImpl
   * @see hwo.evtool.dsl.evalcn.evaluacion.impl.EvaluacionPackageImpl#getEvaluacion()
   * @generated
   */
  int EVALUACION = 6;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EVALUACION__NAME = 0;

  /**
   * The number of structural features of the '<em>Evaluacion</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EVALUACION_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link hwo.evtool.dsl.evalcn.evaluacion.impl.CalificarPropuestaImpl <em>Calificar Propuesta</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see hwo.evtool.dsl.evalcn.evaluacion.impl.CalificarPropuestaImpl
   * @see hwo.evtool.dsl.evalcn.evaluacion.impl.EvaluacionPackageImpl#getCalificarPropuesta()
   * @generated
   */
  int CALIFICAR_PROPUESTA = 7;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CALIFICAR_PROPUESTA__NAME = EVALUACION__NAME;

  /**
   * The feature id for the '<em><b>Tipo</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CALIFICAR_PROPUESTA__TIPO = EVALUACION_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Puntuacion</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CALIFICAR_PROPUESTA__PUNTUACION = EVALUACION_FEATURE_COUNT + 1;

  /**
   * The number of structural features of the '<em>Calificar Propuesta</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CALIFICAR_PROPUESTA_FEATURE_COUNT = EVALUACION_FEATURE_COUNT + 2;

  /**
   * The meta object id for the '{@link hwo.evtool.dsl.evalcn.evaluacion.impl.CalificarEquipoImpl <em>Calificar Equipo</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see hwo.evtool.dsl.evalcn.evaluacion.impl.CalificarEquipoImpl
   * @see hwo.evtool.dsl.evalcn.evaluacion.impl.EvaluacionPackageImpl#getCalificarEquipo()
   * @generated
   */
  int CALIFICAR_EQUIPO = 8;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CALIFICAR_EQUIPO__NAME = EVALUACION__NAME;

  /**
   * The feature id for the '<em><b>Tipo</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CALIFICAR_EQUIPO__TIPO = EVALUACION_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Formacion</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CALIFICAR_EQUIPO__FORMACION = EVALUACION_FEATURE_COUNT + 1;

  /**
   * The feature id for the '<em><b>Formacion Val</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CALIFICAR_EQUIPO__FORMACION_VAL = EVALUACION_FEATURE_COUNT + 2;

  /**
   * The feature id for the '<em><b>Experiencia</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CALIFICAR_EQUIPO__EXPERIENCIA = EVALUACION_FEATURE_COUNT + 3;

  /**
   * The feature id for the '<em><b>Experiencia Val</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CALIFICAR_EQUIPO__EXPERIENCIA_VAL = EVALUACION_FEATURE_COUNT + 4;

  /**
   * The feature id for the '<em><b>Certificacion</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CALIFICAR_EQUIPO__CERTIFICACION = EVALUACION_FEATURE_COUNT + 5;

  /**
   * The feature id for the '<em><b>Certificacion Val</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CALIFICAR_EQUIPO__CERTIFICACION_VAL = EVALUACION_FEATURE_COUNT + 6;

  /**
   * The number of structural features of the '<em>Calificar Equipo</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CALIFICAR_EQUIPO_FEATURE_COUNT = EVALUACION_FEATURE_COUNT + 7;

  /**
   * The meta object id for the '{@link hwo.evtool.dsl.evalcn.evaluacion.impl.CalificarOtrosImpl <em>Calificar Otros</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see hwo.evtool.dsl.evalcn.evaluacion.impl.CalificarOtrosImpl
   * @see hwo.evtool.dsl.evalcn.evaluacion.impl.EvaluacionPackageImpl#getCalificarOtros()
   * @generated
   */
  int CALIFICAR_OTROS = 9;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CALIFICAR_OTROS__NAME = EVALUACION__NAME;

  /**
   * The feature id for the '<em><b>Tipo</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CALIFICAR_OTROS__TIPO = EVALUACION_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Valor</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CALIFICAR_OTROS__VALOR = EVALUACION_FEATURE_COUNT + 1;

  /**
   * The number of structural features of the '<em>Calificar Otros</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CALIFICAR_OTROS_FEATURE_COUNT = EVALUACION_FEATURE_COUNT + 2;

  /**
   * The meta object id for the '{@link hwo.evtool.dsl.evalcn.evaluacion.TipoEquipo <em>Tipo Equipo</em>}' enum.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see hwo.evtool.dsl.evalcn.evaluacion.TipoEquipo
   * @see hwo.evtool.dsl.evalcn.evaluacion.impl.EvaluacionPackageImpl#getTipoEquipo()
   * @generated
   */
  int TIPO_EQUIPO = 10;

  /**
   * The meta object id for the '{@link hwo.evtool.dsl.evalcn.evaluacion.TipoPropuesta <em>Tipo Propuesta</em>}' enum.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see hwo.evtool.dsl.evalcn.evaluacion.TipoPropuesta
   * @see hwo.evtool.dsl.evalcn.evaluacion.impl.EvaluacionPackageImpl#getTipoPropuesta()
   * @generated
   */
  int TIPO_PROPUESTA = 11;

  /**
   * The meta object id for the '{@link hwo.evtool.dsl.evalcn.evaluacion.E_Calificacion <em>ECalificacion</em>}' enum.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see hwo.evtool.dsl.evalcn.evaluacion.E_Calificacion
   * @see hwo.evtool.dsl.evalcn.evaluacion.impl.EvaluacionPackageImpl#getE_Calificacion()
   * @generated
   */
  int ECALIFICACION = 12;


  /**
   * Returns the meta object for class '{@link hwo.evtool.dsl.evalcn.evaluacion.MaquinaEstados <em>Maquina Estados</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Maquina Estados</em>'.
   * @see hwo.evtool.dsl.evalcn.evaluacion.MaquinaEstados
   * @generated
   */
  EClass getMaquinaEstados();

  /**
   * Returns the meta object for the containment reference list '{@link hwo.evtool.dsl.evalcn.evaluacion.MaquinaEstados#getEvents <em>Events</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Events</em>'.
   * @see hwo.evtool.dsl.evalcn.evaluacion.MaquinaEstados#getEvents()
   * @see #getMaquinaEstados()
   * @generated
   */
  EReference getMaquinaEstados_Events();

  /**
   * Returns the meta object for the reference list '{@link hwo.evtool.dsl.evalcn.evaluacion.MaquinaEstados#getResetEvents <em>Reset Events</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference list '<em>Reset Events</em>'.
   * @see hwo.evtool.dsl.evalcn.evaluacion.MaquinaEstados#getResetEvents()
   * @see #getMaquinaEstados()
   * @generated
   */
  EReference getMaquinaEstados_ResetEvents();

  /**
   * Returns the meta object for the containment reference list '{@link hwo.evtool.dsl.evalcn.evaluacion.MaquinaEstados#getCommands <em>Commands</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Commands</em>'.
   * @see hwo.evtool.dsl.evalcn.evaluacion.MaquinaEstados#getCommands()
   * @see #getMaquinaEstados()
   * @generated
   */
  EReference getMaquinaEstados_Commands();

  /**
   * Returns the meta object for the containment reference list '{@link hwo.evtool.dsl.evalcn.evaluacion.MaquinaEstados#getStates <em>States</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>States</em>'.
   * @see hwo.evtool.dsl.evalcn.evaluacion.MaquinaEstados#getStates()
   * @see #getMaquinaEstados()
   * @generated
   */
  EReference getMaquinaEstados_States();

  /**
   * Returns the meta object for class '{@link hwo.evtool.dsl.evalcn.evaluacion.Evento <em>Evento</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Evento</em>'.
   * @see hwo.evtool.dsl.evalcn.evaluacion.Evento
   * @generated
   */
  EClass getEvento();

  /**
   * Returns the meta object for the attribute '{@link hwo.evtool.dsl.evalcn.evaluacion.Evento#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see hwo.evtool.dsl.evalcn.evaluacion.Evento#getName()
   * @see #getEvento()
   * @generated
   */
  EAttribute getEvento_Name();

  /**
   * Returns the meta object for the attribute '{@link hwo.evtool.dsl.evalcn.evaluacion.Evento#getCode <em>Code</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Code</em>'.
   * @see hwo.evtool.dsl.evalcn.evaluacion.Evento#getCode()
   * @see #getEvento()
   * @generated
   */
  EAttribute getEvento_Code();

  /**
   * Returns the meta object for class '{@link hwo.evtool.dsl.evalcn.evaluacion.Componente <em>Componente</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Componente</em>'.
   * @see hwo.evtool.dsl.evalcn.evaluacion.Componente
   * @generated
   */
  EClass getComponente();

  /**
   * Returns the meta object for the attribute '{@link hwo.evtool.dsl.evalcn.evaluacion.Componente#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see hwo.evtool.dsl.evalcn.evaluacion.Componente#getName()
   * @see #getComponente()
   * @generated
   */
  EAttribute getComponente_Name();

  /**
   * Returns the meta object for the reference list '{@link hwo.evtool.dsl.evalcn.evaluacion.Componente#getActions <em>Actions</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference list '<em>Actions</em>'.
   * @see hwo.evtool.dsl.evalcn.evaluacion.Componente#getActions()
   * @see #getComponente()
   * @generated
   */
  EReference getComponente_Actions();

  /**
   * Returns the meta object for the containment reference list '{@link hwo.evtool.dsl.evalcn.evaluacion.Componente#getTransitions <em>Transitions</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Transitions</em>'.
   * @see hwo.evtool.dsl.evalcn.evaluacion.Componente#getTransitions()
   * @see #getComponente()
   * @generated
   */
  EReference getComponente_Transitions();

  /**
   * Returns the meta object for class '{@link hwo.evtool.dsl.evalcn.evaluacion.Expresion <em>Expresion</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Expresion</em>'.
   * @see hwo.evtool.dsl.evalcn.evaluacion.Expresion
   * @generated
   */
  EClass getExpresion();

  /**
   * Returns the meta object for the containment reference '{@link hwo.evtool.dsl.evalcn.evaluacion.Expresion#getTipo <em>Tipo</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Tipo</em>'.
   * @see hwo.evtool.dsl.evalcn.evaluacion.Expresion#getTipo()
   * @see #getExpresion()
   * @generated
   */
  EReference getExpresion_Tipo();

  /**
   * Returns the meta object for the attribute '{@link hwo.evtool.dsl.evalcn.evaluacion.Expresion#getComentario <em>Comentario</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Comentario</em>'.
   * @see hwo.evtool.dsl.evalcn.evaluacion.Expresion#getComentario()
   * @see #getExpresion()
   * @generated
   */
  EAttribute getExpresion_Comentario();

  /**
   * Returns the meta object for class '{@link hwo.evtool.dsl.evalcn.evaluacion.TipoEvaluacion <em>Tipo Evaluacion</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Tipo Evaluacion</em>'.
   * @see hwo.evtool.dsl.evalcn.evaluacion.TipoEvaluacion
   * @generated
   */
  EClass getTipoEvaluacion();

  /**
   * Returns the meta object for the containment reference '{@link hwo.evtool.dsl.evalcn.evaluacion.TipoEvaluacion#getEvaluacion <em>Evaluacion</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Evaluacion</em>'.
   * @see hwo.evtool.dsl.evalcn.evaluacion.TipoEvaluacion#getEvaluacion()
   * @see #getTipoEvaluacion()
   * @generated
   */
  EReference getTipoEvaluacion_Evaluacion();

  /**
   * Returns the meta object for class '{@link hwo.evtool.dsl.evalcn.evaluacion.Transicion <em>Transicion</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Transicion</em>'.
   * @see hwo.evtool.dsl.evalcn.evaluacion.Transicion
   * @generated
   */
  EClass getTransicion();

  /**
   * Returns the meta object for the reference '{@link hwo.evtool.dsl.evalcn.evaluacion.Transicion#getEvent <em>Event</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>Event</em>'.
   * @see hwo.evtool.dsl.evalcn.evaluacion.Transicion#getEvent()
   * @see #getTransicion()
   * @generated
   */
  EReference getTransicion_Event();

  /**
   * Returns the meta object for the reference '{@link hwo.evtool.dsl.evalcn.evaluacion.Transicion#getState <em>State</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>State</em>'.
   * @see hwo.evtool.dsl.evalcn.evaluacion.Transicion#getState()
   * @see #getTransicion()
   * @generated
   */
  EReference getTransicion_State();

  /**
   * Returns the meta object for class '{@link hwo.evtool.dsl.evalcn.evaluacion.Evaluacion <em>Evaluacion</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Evaluacion</em>'.
   * @see hwo.evtool.dsl.evalcn.evaluacion.Evaluacion
   * @generated
   */
  EClass getEvaluacion();

  /**
   * Returns the meta object for the attribute '{@link hwo.evtool.dsl.evalcn.evaluacion.Evaluacion#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see hwo.evtool.dsl.evalcn.evaluacion.Evaluacion#getName()
   * @see #getEvaluacion()
   * @generated
   */
  EAttribute getEvaluacion_Name();

  /**
   * Returns the meta object for class '{@link hwo.evtool.dsl.evalcn.evaluacion.CalificarPropuesta <em>Calificar Propuesta</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Calificar Propuesta</em>'.
   * @see hwo.evtool.dsl.evalcn.evaluacion.CalificarPropuesta
   * @generated
   */
  EClass getCalificarPropuesta();

  /**
   * Returns the meta object for the attribute '{@link hwo.evtool.dsl.evalcn.evaluacion.CalificarPropuesta#getTipo <em>Tipo</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Tipo</em>'.
   * @see hwo.evtool.dsl.evalcn.evaluacion.CalificarPropuesta#getTipo()
   * @see #getCalificarPropuesta()
   * @generated
   */
  EAttribute getCalificarPropuesta_Tipo();

  /**
   * Returns the meta object for the attribute '{@link hwo.evtool.dsl.evalcn.evaluacion.CalificarPropuesta#getPuntuacion <em>Puntuacion</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Puntuacion</em>'.
   * @see hwo.evtool.dsl.evalcn.evaluacion.CalificarPropuesta#getPuntuacion()
   * @see #getCalificarPropuesta()
   * @generated
   */
  EAttribute getCalificarPropuesta_Puntuacion();

  /**
   * Returns the meta object for class '{@link hwo.evtool.dsl.evalcn.evaluacion.CalificarEquipo <em>Calificar Equipo</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Calificar Equipo</em>'.
   * @see hwo.evtool.dsl.evalcn.evaluacion.CalificarEquipo
   * @generated
   */
  EClass getCalificarEquipo();

  /**
   * Returns the meta object for the attribute '{@link hwo.evtool.dsl.evalcn.evaluacion.CalificarEquipo#getTipo <em>Tipo</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Tipo</em>'.
   * @see hwo.evtool.dsl.evalcn.evaluacion.CalificarEquipo#getTipo()
   * @see #getCalificarEquipo()
   * @generated
   */
  EAttribute getCalificarEquipo_Tipo();

  /**
   * Returns the meta object for the attribute '{@link hwo.evtool.dsl.evalcn.evaluacion.CalificarEquipo#getFormacion <em>Formacion</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Formacion</em>'.
   * @see hwo.evtool.dsl.evalcn.evaluacion.CalificarEquipo#getFormacion()
   * @see #getCalificarEquipo()
   * @generated
   */
  EAttribute getCalificarEquipo_Formacion();

  /**
   * Returns the meta object for the attribute '{@link hwo.evtool.dsl.evalcn.evaluacion.CalificarEquipo#getFormacionVal <em>Formacion Val</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Formacion Val</em>'.
   * @see hwo.evtool.dsl.evalcn.evaluacion.CalificarEquipo#getFormacionVal()
   * @see #getCalificarEquipo()
   * @generated
   */
  EAttribute getCalificarEquipo_FormacionVal();

  /**
   * Returns the meta object for the attribute '{@link hwo.evtool.dsl.evalcn.evaluacion.CalificarEquipo#getExperiencia <em>Experiencia</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Experiencia</em>'.
   * @see hwo.evtool.dsl.evalcn.evaluacion.CalificarEquipo#getExperiencia()
   * @see #getCalificarEquipo()
   * @generated
   */
  EAttribute getCalificarEquipo_Experiencia();

  /**
   * Returns the meta object for the attribute '{@link hwo.evtool.dsl.evalcn.evaluacion.CalificarEquipo#getExperienciaVal <em>Experiencia Val</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Experiencia Val</em>'.
   * @see hwo.evtool.dsl.evalcn.evaluacion.CalificarEquipo#getExperienciaVal()
   * @see #getCalificarEquipo()
   * @generated
   */
  EAttribute getCalificarEquipo_ExperienciaVal();

  /**
   * Returns the meta object for the attribute '{@link hwo.evtool.dsl.evalcn.evaluacion.CalificarEquipo#getCertificacion <em>Certificacion</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Certificacion</em>'.
   * @see hwo.evtool.dsl.evalcn.evaluacion.CalificarEquipo#getCertificacion()
   * @see #getCalificarEquipo()
   * @generated
   */
  EAttribute getCalificarEquipo_Certificacion();

  /**
   * Returns the meta object for the attribute '{@link hwo.evtool.dsl.evalcn.evaluacion.CalificarEquipo#getCertificacionVal <em>Certificacion Val</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Certificacion Val</em>'.
   * @see hwo.evtool.dsl.evalcn.evaluacion.CalificarEquipo#getCertificacionVal()
   * @see #getCalificarEquipo()
   * @generated
   */
  EAttribute getCalificarEquipo_CertificacionVal();

  /**
   * Returns the meta object for class '{@link hwo.evtool.dsl.evalcn.evaluacion.CalificarOtros <em>Calificar Otros</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Calificar Otros</em>'.
   * @see hwo.evtool.dsl.evalcn.evaluacion.CalificarOtros
   * @generated
   */
  EClass getCalificarOtros();

  /**
   * Returns the meta object for the attribute '{@link hwo.evtool.dsl.evalcn.evaluacion.CalificarOtros#getTipo <em>Tipo</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Tipo</em>'.
   * @see hwo.evtool.dsl.evalcn.evaluacion.CalificarOtros#getTipo()
   * @see #getCalificarOtros()
   * @generated
   */
  EAttribute getCalificarOtros_Tipo();

  /**
   * Returns the meta object for the attribute '{@link hwo.evtool.dsl.evalcn.evaluacion.CalificarOtros#getValor <em>Valor</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Valor</em>'.
   * @see hwo.evtool.dsl.evalcn.evaluacion.CalificarOtros#getValor()
   * @see #getCalificarOtros()
   * @generated
   */
  EAttribute getCalificarOtros_Valor();

  /**
   * Returns the meta object for enum '{@link hwo.evtool.dsl.evalcn.evaluacion.TipoEquipo <em>Tipo Equipo</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for enum '<em>Tipo Equipo</em>'.
   * @see hwo.evtool.dsl.evalcn.evaluacion.TipoEquipo
   * @generated
   */
  EEnum getTipoEquipo();

  /**
   * Returns the meta object for enum '{@link hwo.evtool.dsl.evalcn.evaluacion.TipoPropuesta <em>Tipo Propuesta</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for enum '<em>Tipo Propuesta</em>'.
   * @see hwo.evtool.dsl.evalcn.evaluacion.TipoPropuesta
   * @generated
   */
  EEnum getTipoPropuesta();

  /**
   * Returns the meta object for enum '{@link hwo.evtool.dsl.evalcn.evaluacion.E_Calificacion <em>ECalificacion</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for enum '<em>ECalificacion</em>'.
   * @see hwo.evtool.dsl.evalcn.evaluacion.E_Calificacion
   * @generated
   */
  EEnum getE_Calificacion();

  /**
   * Returns the factory that creates the instances of the model.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the factory that creates the instances of the model.
   * @generated
   */
  EvaluacionFactory getEvaluacionFactory();

  /**
   * <!-- begin-user-doc -->
   * Defines literals for the meta objects that represent
   * <ul>
   *   <li>each class,</li>
   *   <li>each feature of each class,</li>
   *   <li>each enum,</li>
   *   <li>and each data type</li>
   * </ul>
   * <!-- end-user-doc -->
   * @generated
   */
  interface Literals
  {
    /**
     * The meta object literal for the '{@link hwo.evtool.dsl.evalcn.evaluacion.impl.MaquinaEstadosImpl <em>Maquina Estados</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see hwo.evtool.dsl.evalcn.evaluacion.impl.MaquinaEstadosImpl
     * @see hwo.evtool.dsl.evalcn.evaluacion.impl.EvaluacionPackageImpl#getMaquinaEstados()
     * @generated
     */
    EClass MAQUINA_ESTADOS = eINSTANCE.getMaquinaEstados();

    /**
     * The meta object literal for the '<em><b>Events</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference MAQUINA_ESTADOS__EVENTS = eINSTANCE.getMaquinaEstados_Events();

    /**
     * The meta object literal for the '<em><b>Reset Events</b></em>' reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference MAQUINA_ESTADOS__RESET_EVENTS = eINSTANCE.getMaquinaEstados_ResetEvents();

    /**
     * The meta object literal for the '<em><b>Commands</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference MAQUINA_ESTADOS__COMMANDS = eINSTANCE.getMaquinaEstados_Commands();

    /**
     * The meta object literal for the '<em><b>States</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference MAQUINA_ESTADOS__STATES = eINSTANCE.getMaquinaEstados_States();

    /**
     * The meta object literal for the '{@link hwo.evtool.dsl.evalcn.evaluacion.impl.EventoImpl <em>Evento</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see hwo.evtool.dsl.evalcn.evaluacion.impl.EventoImpl
     * @see hwo.evtool.dsl.evalcn.evaluacion.impl.EvaluacionPackageImpl#getEvento()
     * @generated
     */
    EClass EVENTO = eINSTANCE.getEvento();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute EVENTO__NAME = eINSTANCE.getEvento_Name();

    /**
     * The meta object literal for the '<em><b>Code</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute EVENTO__CODE = eINSTANCE.getEvento_Code();

    /**
     * The meta object literal for the '{@link hwo.evtool.dsl.evalcn.evaluacion.impl.ComponenteImpl <em>Componente</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see hwo.evtool.dsl.evalcn.evaluacion.impl.ComponenteImpl
     * @see hwo.evtool.dsl.evalcn.evaluacion.impl.EvaluacionPackageImpl#getComponente()
     * @generated
     */
    EClass COMPONENTE = eINSTANCE.getComponente();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute COMPONENTE__NAME = eINSTANCE.getComponente_Name();

    /**
     * The meta object literal for the '<em><b>Actions</b></em>' reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference COMPONENTE__ACTIONS = eINSTANCE.getComponente_Actions();

    /**
     * The meta object literal for the '<em><b>Transitions</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference COMPONENTE__TRANSITIONS = eINSTANCE.getComponente_Transitions();

    /**
     * The meta object literal for the '{@link hwo.evtool.dsl.evalcn.evaluacion.impl.ExpresionImpl <em>Expresion</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see hwo.evtool.dsl.evalcn.evaluacion.impl.ExpresionImpl
     * @see hwo.evtool.dsl.evalcn.evaluacion.impl.EvaluacionPackageImpl#getExpresion()
     * @generated
     */
    EClass EXPRESION = eINSTANCE.getExpresion();

    /**
     * The meta object literal for the '<em><b>Tipo</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference EXPRESION__TIPO = eINSTANCE.getExpresion_Tipo();

    /**
     * The meta object literal for the '<em><b>Comentario</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute EXPRESION__COMENTARIO = eINSTANCE.getExpresion_Comentario();

    /**
     * The meta object literal for the '{@link hwo.evtool.dsl.evalcn.evaluacion.impl.TipoEvaluacionImpl <em>Tipo Evaluacion</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see hwo.evtool.dsl.evalcn.evaluacion.impl.TipoEvaluacionImpl
     * @see hwo.evtool.dsl.evalcn.evaluacion.impl.EvaluacionPackageImpl#getTipoEvaluacion()
     * @generated
     */
    EClass TIPO_EVALUACION = eINSTANCE.getTipoEvaluacion();

    /**
     * The meta object literal for the '<em><b>Evaluacion</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference TIPO_EVALUACION__EVALUACION = eINSTANCE.getTipoEvaluacion_Evaluacion();

    /**
     * The meta object literal for the '{@link hwo.evtool.dsl.evalcn.evaluacion.impl.TransicionImpl <em>Transicion</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see hwo.evtool.dsl.evalcn.evaluacion.impl.TransicionImpl
     * @see hwo.evtool.dsl.evalcn.evaluacion.impl.EvaluacionPackageImpl#getTransicion()
     * @generated
     */
    EClass TRANSICION = eINSTANCE.getTransicion();

    /**
     * The meta object literal for the '<em><b>Event</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference TRANSICION__EVENT = eINSTANCE.getTransicion_Event();

    /**
     * The meta object literal for the '<em><b>State</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference TRANSICION__STATE = eINSTANCE.getTransicion_State();

    /**
     * The meta object literal for the '{@link hwo.evtool.dsl.evalcn.evaluacion.impl.EvaluacionImpl <em>Evaluacion</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see hwo.evtool.dsl.evalcn.evaluacion.impl.EvaluacionImpl
     * @see hwo.evtool.dsl.evalcn.evaluacion.impl.EvaluacionPackageImpl#getEvaluacion()
     * @generated
     */
    EClass EVALUACION = eINSTANCE.getEvaluacion();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute EVALUACION__NAME = eINSTANCE.getEvaluacion_Name();

    /**
     * The meta object literal for the '{@link hwo.evtool.dsl.evalcn.evaluacion.impl.CalificarPropuestaImpl <em>Calificar Propuesta</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see hwo.evtool.dsl.evalcn.evaluacion.impl.CalificarPropuestaImpl
     * @see hwo.evtool.dsl.evalcn.evaluacion.impl.EvaluacionPackageImpl#getCalificarPropuesta()
     * @generated
     */
    EClass CALIFICAR_PROPUESTA = eINSTANCE.getCalificarPropuesta();

    /**
     * The meta object literal for the '<em><b>Tipo</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute CALIFICAR_PROPUESTA__TIPO = eINSTANCE.getCalificarPropuesta_Tipo();

    /**
     * The meta object literal for the '<em><b>Puntuacion</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute CALIFICAR_PROPUESTA__PUNTUACION = eINSTANCE.getCalificarPropuesta_Puntuacion();

    /**
     * The meta object literal for the '{@link hwo.evtool.dsl.evalcn.evaluacion.impl.CalificarEquipoImpl <em>Calificar Equipo</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see hwo.evtool.dsl.evalcn.evaluacion.impl.CalificarEquipoImpl
     * @see hwo.evtool.dsl.evalcn.evaluacion.impl.EvaluacionPackageImpl#getCalificarEquipo()
     * @generated
     */
    EClass CALIFICAR_EQUIPO = eINSTANCE.getCalificarEquipo();

    /**
     * The meta object literal for the '<em><b>Tipo</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute CALIFICAR_EQUIPO__TIPO = eINSTANCE.getCalificarEquipo_Tipo();

    /**
     * The meta object literal for the '<em><b>Formacion</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute CALIFICAR_EQUIPO__FORMACION = eINSTANCE.getCalificarEquipo_Formacion();

    /**
     * The meta object literal for the '<em><b>Formacion Val</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute CALIFICAR_EQUIPO__FORMACION_VAL = eINSTANCE.getCalificarEquipo_FormacionVal();

    /**
     * The meta object literal for the '<em><b>Experiencia</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute CALIFICAR_EQUIPO__EXPERIENCIA = eINSTANCE.getCalificarEquipo_Experiencia();

    /**
     * The meta object literal for the '<em><b>Experiencia Val</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute CALIFICAR_EQUIPO__EXPERIENCIA_VAL = eINSTANCE.getCalificarEquipo_ExperienciaVal();

    /**
     * The meta object literal for the '<em><b>Certificacion</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute CALIFICAR_EQUIPO__CERTIFICACION = eINSTANCE.getCalificarEquipo_Certificacion();

    /**
     * The meta object literal for the '<em><b>Certificacion Val</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute CALIFICAR_EQUIPO__CERTIFICACION_VAL = eINSTANCE.getCalificarEquipo_CertificacionVal();

    /**
     * The meta object literal for the '{@link hwo.evtool.dsl.evalcn.evaluacion.impl.CalificarOtrosImpl <em>Calificar Otros</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see hwo.evtool.dsl.evalcn.evaluacion.impl.CalificarOtrosImpl
     * @see hwo.evtool.dsl.evalcn.evaluacion.impl.EvaluacionPackageImpl#getCalificarOtros()
     * @generated
     */
    EClass CALIFICAR_OTROS = eINSTANCE.getCalificarOtros();

    /**
     * The meta object literal for the '<em><b>Tipo</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute CALIFICAR_OTROS__TIPO = eINSTANCE.getCalificarOtros_Tipo();

    /**
     * The meta object literal for the '<em><b>Valor</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute CALIFICAR_OTROS__VALOR = eINSTANCE.getCalificarOtros_Valor();

    /**
     * The meta object literal for the '{@link hwo.evtool.dsl.evalcn.evaluacion.TipoEquipo <em>Tipo Equipo</em>}' enum.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see hwo.evtool.dsl.evalcn.evaluacion.TipoEquipo
     * @see hwo.evtool.dsl.evalcn.evaluacion.impl.EvaluacionPackageImpl#getTipoEquipo()
     * @generated
     */
    EEnum TIPO_EQUIPO = eINSTANCE.getTipoEquipo();

    /**
     * The meta object literal for the '{@link hwo.evtool.dsl.evalcn.evaluacion.TipoPropuesta <em>Tipo Propuesta</em>}' enum.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see hwo.evtool.dsl.evalcn.evaluacion.TipoPropuesta
     * @see hwo.evtool.dsl.evalcn.evaluacion.impl.EvaluacionPackageImpl#getTipoPropuesta()
     * @generated
     */
    EEnum TIPO_PROPUESTA = eINSTANCE.getTipoPropuesta();

    /**
     * The meta object literal for the '{@link hwo.evtool.dsl.evalcn.evaluacion.E_Calificacion <em>ECalificacion</em>}' enum.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see hwo.evtool.dsl.evalcn.evaluacion.E_Calificacion
     * @see hwo.evtool.dsl.evalcn.evaluacion.impl.EvaluacionPackageImpl#getE_Calificacion()
     * @generated
     */
    EEnum ECALIFICACION = eINSTANCE.getE_Calificacion();

  }

} //EvaluacionPackage
