/*
 * generated by Xtext 2.25.0
 */
package hwo.evtool.dsl.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractEvaluacionScopeProvider extends DelegatingScopeProvider {
}
