/**
 * generated by Xtext 2.25.0
 */
package hwo.evtool.dsl.evalcn.evaluacion.impl;

import hwo.evtool.dsl.evalcn.evaluacion.CalificarEquipo;
import hwo.evtool.dsl.evalcn.evaluacion.EvaluacionPackage;
import hwo.evtool.dsl.evalcn.evaluacion.TipoEquipo;

import org.eclipse.emf.common.notify.Notification;

import org.eclipse.emf.ecore.EClass;

import org.eclipse.emf.ecore.impl.ENotificationImpl;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Calificar Equipo</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link hwo.evtool.dsl.evalcn.evaluacion.impl.CalificarEquipoImpl#getTipo <em>Tipo</em>}</li>
 *   <li>{@link hwo.evtool.dsl.evalcn.evaluacion.impl.CalificarEquipoImpl#getNumerador <em>Numerador</em>}</li>
 *   <li>{@link hwo.evtool.dsl.evalcn.evaluacion.impl.CalificarEquipoImpl#getDenominador <em>Denominador</em>}</li>
 * </ul>
 *
 * @generated
 */
public class CalificarEquipoImpl extends EvaluacionImpl implements CalificarEquipo
{
  /**
   * The default value of the '{@link #getTipo() <em>Tipo</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getTipo()
   * @generated
   * @ordered
   */
  protected static final TipoEquipo TIPO_EDEFAULT = TipoEquipo.EVALUAR_ARQUITECTO;

  /**
   * The cached value of the '{@link #getTipo() <em>Tipo</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getTipo()
   * @generated
   * @ordered
   */
  protected TipoEquipo tipo = TIPO_EDEFAULT;

  /**
   * The default value of the '{@link #getNumerador() <em>Numerador</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getNumerador()
   * @generated
   * @ordered
   */
  protected static final int NUMERADOR_EDEFAULT = 0;

  /**
   * The cached value of the '{@link #getNumerador() <em>Numerador</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getNumerador()
   * @generated
   * @ordered
   */
  protected int numerador = NUMERADOR_EDEFAULT;

  /**
   * The default value of the '{@link #getDenominador() <em>Denominador</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getDenominador()
   * @generated
   * @ordered
   */
  protected static final int DENOMINADOR_EDEFAULT = 0;

  /**
   * The cached value of the '{@link #getDenominador() <em>Denominador</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getDenominador()
   * @generated
   * @ordered
   */
  protected int denominador = DENOMINADOR_EDEFAULT;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected CalificarEquipoImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return EvaluacionPackage.Literals.CALIFICAR_EQUIPO;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public TipoEquipo getTipo()
  {
    return tipo;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setTipo(TipoEquipo newTipo)
  {
    TipoEquipo oldTipo = tipo;
    tipo = newTipo == null ? TIPO_EDEFAULT : newTipo;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, EvaluacionPackage.CALIFICAR_EQUIPO__TIPO, oldTipo, tipo));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public int getNumerador()
  {
    return numerador;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setNumerador(int newNumerador)
  {
    int oldNumerador = numerador;
    numerador = newNumerador;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, EvaluacionPackage.CALIFICAR_EQUIPO__NUMERADOR, oldNumerador, numerador));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public int getDenominador()
  {
    return denominador;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setDenominador(int newDenominador)
  {
    int oldDenominador = denominador;
    denominador = newDenominador;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, EvaluacionPackage.CALIFICAR_EQUIPO__DENOMINADOR, oldDenominador, denominador));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case EvaluacionPackage.CALIFICAR_EQUIPO__TIPO:
        return getTipo();
      case EvaluacionPackage.CALIFICAR_EQUIPO__NUMERADOR:
        return getNumerador();
      case EvaluacionPackage.CALIFICAR_EQUIPO__DENOMINADOR:
        return getDenominador();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case EvaluacionPackage.CALIFICAR_EQUIPO__TIPO:
        setTipo((TipoEquipo)newValue);
        return;
      case EvaluacionPackage.CALIFICAR_EQUIPO__NUMERADOR:
        setNumerador((Integer)newValue);
        return;
      case EvaluacionPackage.CALIFICAR_EQUIPO__DENOMINADOR:
        setDenominador((Integer)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case EvaluacionPackage.CALIFICAR_EQUIPO__TIPO:
        setTipo(TIPO_EDEFAULT);
        return;
      case EvaluacionPackage.CALIFICAR_EQUIPO__NUMERADOR:
        setNumerador(NUMERADOR_EDEFAULT);
        return;
      case EvaluacionPackage.CALIFICAR_EQUIPO__DENOMINADOR:
        setDenominador(DENOMINADOR_EDEFAULT);
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case EvaluacionPackage.CALIFICAR_EQUIPO__TIPO:
        return tipo != TIPO_EDEFAULT;
      case EvaluacionPackage.CALIFICAR_EQUIPO__NUMERADOR:
        return numerador != NUMERADOR_EDEFAULT;
      case EvaluacionPackage.CALIFICAR_EQUIPO__DENOMINADOR:
        return denominador != DENOMINADOR_EDEFAULT;
    }
    return super.eIsSet(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String toString()
  {
    if (eIsProxy()) return super.toString();

    StringBuilder result = new StringBuilder(super.toString());
    result.append(" (tipo: ");
    result.append(tipo);
    result.append(", numerador: ");
    result.append(numerador);
    result.append(", denominador: ");
    result.append(denominador);
    result.append(')');
    return result.toString();
  }

} //CalificarEquipoImpl
