/*
 * generated by Xtext 2.25.0
 */
package hwo.evtool.dsl.evalcn.web;


/**
 * Use this class to register additional components to be used within the web application.
 */
public class EvaluacionWebModule extends AbstractEvaluacionWebModule {
}
