/*
 * generated by Xtext 2.25.0
 */
package hwo.evtool.dsl.evalcn.web;

import com.google.inject.Guice;
import com.google.inject.Injector;
import hwo.evtool.dsl.evalcn.EvaluacionRuntimeModule;
import hwo.evtool.dsl.evalcn.EvaluacionStandaloneSetup;
import hwo.evtool.dsl.evalcn.ide.EvaluacionIdeModule;
import org.eclipse.xtext.util.Modules2;

/**
 * Initialization support for running Xtext languages in web applications.
 */
public class EvaluacionWebSetup extends EvaluacionStandaloneSetup {
	
	@Override
	public Injector createInjector() {
		return Guice.createInjector(Modules2.mixin(new EvaluacionRuntimeModule(), new EvaluacionIdeModule(), new EvaluacionWebModule()));
	}
	
}
